/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';
import {
  getPermissionsDecoder,
  getPermissionsEncoder,
  type Permissions,
  type PermissionsArgs,
} from '.';

export type Member = { key: Address; permissions: Permissions };

export type MemberArgs = { key: Address; permissions: PermissionsArgs };

export function getMemberEncoder(): FixedSizeEncoder<MemberArgs> {
  return getStructEncoder([
    ['key', getAddressEncoder()],
    ['permissions', getPermissionsEncoder()],
  ]);
}

export function getMemberDecoder(): FixedSizeDecoder<Member> {
  return getStructDecoder([
    ['key', getAddressDecoder()],
    ['permissions', getPermissionsDecoder()],
  ]);
}

export function getMemberCodec(): FixedSizeCodec<MemberArgs, Member> {
  return combineCodec(getMemberEncoder(), getMemberDecoder());
}
