/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

/** Bitmask for permissions. */
export type Permissions = { mask: number };

export type PermissionsArgs = Permissions;

export function getPermissionsEncoder(): FixedSizeEncoder<PermissionsArgs> {
  return getStructEncoder([['mask', getU8Encoder()]]);
}

export function getPermissionsDecoder(): FixedSizeDecoder<Permissions> {
  return getStructDecoder([['mask', getU8Decoder()]]);
}

export function getPermissionsCodec(): FixedSizeCodec<
  PermissionsArgs,
  Permissions
> {
  return combineCodec(getPermissionsEncoder(), getPermissionsDecoder());
}
