/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  getOptionDecoder,
  getOptionEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  type Codec,
  type Decoder,
  type Encoder,
  type Option,
  type OptionOrNullable,
} from '@solana/kit';

export type ProposalVoteArgs = { memo: Option<string> };

export type ProposalVoteArgsArgs = { memo: OptionOrNullable<string> };

export function getProposalVoteArgsEncoder(): Encoder<ProposalVoteArgsArgs> {
  return getStructEncoder([
    [
      'memo',
      getOptionEncoder(addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())),
    ],
  ]);
}

export function getProposalVoteArgsDecoder(): Decoder<ProposalVoteArgs> {
  return getStructDecoder([
    [
      'memo',
      getOptionDecoder(addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())),
    ],
  ]);
}

export function getProposalVoteArgsCodec(): Codec<
  ProposalVoteArgsArgs,
  ProposalVoteArgs
> {
  return combineCodec(
    getProposalVoteArgsEncoder(),
    getProposalVoteArgsDecoder()
  );
}
