/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  getBytesDecoder,
  getBytesEncoder,
  getOptionDecoder,
  getOptionEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU8Decoder,
  getU8Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  type Codec,
  type Decoder,
  type Encoder,
  type Option,
  type OptionOrNullable,
  type ReadonlyUint8Array,
} from '@solana/kit';

export type VaultTransactionCreateArgs = {
  /** Index of the vault this transaction belongs to. */
  vaultIndex: number;
  /** Number of ephemeral signing PDAs required by the transaction. */
  ephemeralSigners: number;
  transactionMessage: ReadonlyUint8Array;
  memo: Option<string>;
};

export type VaultTransactionCreateArgsArgs = {
  /** Index of the vault this transaction belongs to. */
  vaultIndex: number;
  /** Number of ephemeral signing PDAs required by the transaction. */
  ephemeralSigners: number;
  transactionMessage: ReadonlyUint8Array;
  memo: OptionOrNullable<string>;
};

export function getVaultTransactionCreateArgsEncoder(): Encoder<VaultTransactionCreateArgsArgs> {
  return getStructEncoder([
    ['vaultIndex', getU8Encoder()],
    ['ephemeralSigners', getU8Encoder()],
    [
      'transactionMessage',
      addEncoderSizePrefix(getBytesEncoder(), getU32Encoder()),
    ],
    [
      'memo',
      getOptionEncoder(addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())),
    ],
  ]);
}

export function getVaultTransactionCreateArgsDecoder(): Decoder<VaultTransactionCreateArgs> {
  return getStructDecoder([
    ['vaultIndex', getU8Decoder()],
    ['ephemeralSigners', getU8Decoder()],
    [
      'transactionMessage',
      addDecoderSizePrefix(getBytesDecoder(), getU32Decoder()),
    ],
    [
      'memo',
      getOptionDecoder(addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())),
    ],
  ]);
}

export function getVaultTransactionCreateArgsCodec(): Codec<
  VaultTransactionCreateArgsArgs,
  VaultTransactionCreateArgs
> {
  return combineCodec(
    getVaultTransactionCreateArgsEncoder(),
    getVaultTransactionCreateArgsDecoder()
  );
}
