/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export enum Vote {
  Approve,
  Reject,
  Cancel,
}

export type VoteArgs = Vote;

export function getVoteEncoder(): FixedSizeEncoder<VoteArgs> {
  return getEnumEncoder(Vote);
}

export function getVoteDecoder(): FixedSizeDecoder<Vote> {
  return getEnumDecoder(Vote);
}

export function getVoteCodec(): FixedSizeCodec<VoteArgs, Vote> {
  return combineCodec(getVoteEncoder(), getVoteDecoder());
}
