/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const BATCH_ADD_TRANSACTION_DISCRIMINATOR = new Uint8Array([
  89, 100, 224, 18, 69, 70, 54, 76,
]);

export function getBatchAddTransactionDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    BATCH_ADD_TRANSACTION_DISCRIMINATOR
  );
}

export type BatchAddTransactionInstruction<
  TProgram extends string = typeof SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS,
  TAccountMultisig extends string | AccountMeta<string> = string,
  TAccountProposal extends string | AccountMeta<string> = string,
  TAccountBatch extends string | AccountMeta<string> = string,
  TAccountTransaction extends string | AccountMeta<string> = string,
  TAccountMember extends string | AccountMeta<string> = string,
  TAccountRentPayer extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountMultisig extends string
        ? ReadonlyAccount<TAccountMultisig>
        : TAccountMultisig,
      TAccountProposal extends string
        ? ReadonlyAccount<TAccountProposal>
        : TAccountProposal,
      TAccountBatch extends string
        ? WritableAccount<TAccountBatch>
        : TAccountBatch,
      TAccountTransaction extends string
        ? WritableAccount<TAccountTransaction>
        : TAccountTransaction,
      TAccountMember extends string
        ? ReadonlySignerAccount<TAccountMember> &
            AccountSignerMeta<TAccountMember>
        : TAccountMember,
      TAccountRentPayer extends string
        ? WritableSignerAccount<TAccountRentPayer> &
            AccountSignerMeta<TAccountRentPayer>
        : TAccountRentPayer,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type BatchAddTransactionInstructionData = {
  discriminator: ReadonlyUint8Array;
  /** Number of ephemeral signing PDAs required by the transaction. */
  ephemeralSigners: number;
  transactionMessage: ReadonlyUint8Array;
};

export type BatchAddTransactionInstructionDataArgs = {
  /** Number of ephemeral signing PDAs required by the transaction. */
  ephemeralSigners: number;
  transactionMessage: ReadonlyUint8Array;
};

export function getBatchAddTransactionInstructionDataEncoder(): Encoder<BatchAddTransactionInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['ephemeralSigners', getU8Encoder()],
      [
        'transactionMessage',
        addEncoderSizePrefix(getBytesEncoder(), getU32Encoder()),
      ],
    ]),
    (value) => ({
      ...value,
      discriminator: BATCH_ADD_TRANSACTION_DISCRIMINATOR,
    })
  );
}

export function getBatchAddTransactionInstructionDataDecoder(): Decoder<BatchAddTransactionInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['ephemeralSigners', getU8Decoder()],
    [
      'transactionMessage',
      addDecoderSizePrefix(getBytesDecoder(), getU32Decoder()),
    ],
  ]);
}

export function getBatchAddTransactionInstructionDataCodec(): Codec<
  BatchAddTransactionInstructionDataArgs,
  BatchAddTransactionInstructionData
> {
  return combineCodec(
    getBatchAddTransactionInstructionDataEncoder(),
    getBatchAddTransactionInstructionDataDecoder()
  );
}

export type BatchAddTransactionInput<
  TAccountMultisig extends string = string,
  TAccountProposal extends string = string,
  TAccountBatch extends string = string,
  TAccountTransaction extends string = string,
  TAccountMember extends string = string,
  TAccountRentPayer extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** Multisig account this batch belongs to. */
  multisig: Address<TAccountMultisig>;
  /** The proposal account associated with the batch. */
  proposal: Address<TAccountProposal>;
  batch: Address<TAccountBatch>;
  /** `VaultBatchTransaction` account to initialize and add to the `batch`. */
  transaction: Address<TAccountTransaction>;
  /** Member of the multisig. */
  member: TransactionSigner<TAccountMember>;
  /** The payer for the batch transaction account rent. */
  rentPayer: TransactionSigner<TAccountRentPayer>;
  systemProgram?: Address<TAccountSystemProgram>;
  ephemeralSigners: BatchAddTransactionInstructionDataArgs['ephemeralSigners'];
  transactionMessage: BatchAddTransactionInstructionDataArgs['transactionMessage'];
};

export function getBatchAddTransactionInstruction<
  TAccountMultisig extends string,
  TAccountProposal extends string,
  TAccountBatch extends string,
  TAccountTransaction extends string,
  TAccountMember extends string,
  TAccountRentPayer extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends
    Address = typeof SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS,
>(
  input: BatchAddTransactionInput<
    TAccountMultisig,
    TAccountProposal,
    TAccountBatch,
    TAccountTransaction,
    TAccountMember,
    TAccountRentPayer,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): BatchAddTransactionInstruction<
  TProgramAddress,
  TAccountMultisig,
  TAccountProposal,
  TAccountBatch,
  TAccountTransaction,
  TAccountMember,
  TAccountRentPayer,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    multisig: { value: input.multisig ?? null, isWritable: false },
    proposal: { value: input.proposal ?? null, isWritable: false },
    batch: { value: input.batch ?? null, isWritable: true },
    transaction: { value: input.transaction ?? null, isWritable: true },
    member: { value: input.member ?? null, isWritable: false },
    rentPayer: { value: input.rentPayer ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.multisig),
      getAccountMeta(accounts.proposal),
      getAccountMeta(accounts.batch),
      getAccountMeta(accounts.transaction),
      getAccountMeta(accounts.member),
      getAccountMeta(accounts.rentPayer),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getBatchAddTransactionInstructionDataEncoder().encode(
      args as BatchAddTransactionInstructionDataArgs
    ),
  } as BatchAddTransactionInstruction<
    TProgramAddress,
    TAccountMultisig,
    TAccountProposal,
    TAccountBatch,
    TAccountTransaction,
    TAccountMember,
    TAccountRentPayer,
    TAccountSystemProgram
  >;

  return instruction;
}

export type ParsedBatchAddTransactionInstruction<
  TProgram extends string = typeof SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Multisig account this batch belongs to. */
    multisig: TAccountMetas[0];
    /** The proposal account associated with the batch. */
    proposal: TAccountMetas[1];
    batch: TAccountMetas[2];
    /** `VaultBatchTransaction` account to initialize and add to the `batch`. */
    transaction: TAccountMetas[3];
    /** Member of the multisig. */
    member: TAccountMetas[4];
    /** The payer for the batch transaction account rent. */
    rentPayer: TAccountMetas[5];
    systemProgram: TAccountMetas[6];
  };
  data: BatchAddTransactionInstructionData;
};

export function parseBatchAddTransactionInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedBatchAddTransactionInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      multisig: getNextAccount(),
      proposal: getNextAccount(),
      batch: getNextAccount(),
      transaction: getNextAccount(),
      member: getNextAccount(),
      rentPayer: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getBatchAddTransactionInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
