/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const BATCH_EXECUTE_TRANSACTION_DISCRIMINATOR = new Uint8Array([
  172, 44, 179, 152, 21, 127, 234, 180,
]);

export function getBatchExecuteTransactionDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    BATCH_EXECUTE_TRANSACTION_DISCRIMINATOR
  );
}

export type BatchExecuteTransactionInstruction<
  TProgram extends string = typeof SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS,
  TAccountMultisig extends string | AccountMeta<string> = string,
  TAccountMember extends string | AccountMeta<string> = string,
  TAccountProposal extends string | AccountMeta<string> = string,
  TAccountBatch extends string | AccountMeta<string> = string,
  TAccountTransaction extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountMultisig extends string
        ? ReadonlyAccount<TAccountMultisig>
        : TAccountMultisig,
      TAccountMember extends string
        ? ReadonlySignerAccount<TAccountMember> &
            AccountSignerMeta<TAccountMember>
        : TAccountMember,
      TAccountProposal extends string
        ? WritableAccount<TAccountProposal>
        : TAccountProposal,
      TAccountBatch extends string
        ? WritableAccount<TAccountBatch>
        : TAccountBatch,
      TAccountTransaction extends string
        ? ReadonlyAccount<TAccountTransaction>
        : TAccountTransaction,
      ...TRemainingAccounts,
    ]
  >;

export type BatchExecuteTransactionInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type BatchExecuteTransactionInstructionDataArgs = {};

export function getBatchExecuteTransactionInstructionDataEncoder(): FixedSizeEncoder<BatchExecuteTransactionInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({
      ...value,
      discriminator: BATCH_EXECUTE_TRANSACTION_DISCRIMINATOR,
    })
  );
}

export function getBatchExecuteTransactionInstructionDataDecoder(): FixedSizeDecoder<BatchExecuteTransactionInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getBatchExecuteTransactionInstructionDataCodec(): FixedSizeCodec<
  BatchExecuteTransactionInstructionDataArgs,
  BatchExecuteTransactionInstructionData
> {
  return combineCodec(
    getBatchExecuteTransactionInstructionDataEncoder(),
    getBatchExecuteTransactionInstructionDataDecoder()
  );
}

export type BatchExecuteTransactionInput<
  TAccountMultisig extends string = string,
  TAccountMember extends string = string,
  TAccountProposal extends string = string,
  TAccountBatch extends string = string,
  TAccountTransaction extends string = string,
> = {
  /** Multisig account this batch belongs to. */
  multisig: Address<TAccountMultisig>;
  /** Member of the multisig. */
  member: TransactionSigner<TAccountMember>;
  /**
   * The proposal account associated with the batch.
   * If `transaction` is the last in the batch, the `proposal` status will be set to `Executed`.
   */
  proposal: Address<TAccountProposal>;
  batch: Address<TAccountBatch>;
  /** Batch transaction to execute. */
  transaction: Address<TAccountTransaction>;
};

export function getBatchExecuteTransactionInstruction<
  TAccountMultisig extends string,
  TAccountMember extends string,
  TAccountProposal extends string,
  TAccountBatch extends string,
  TAccountTransaction extends string,
  TProgramAddress extends
    Address = typeof SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS,
>(
  input: BatchExecuteTransactionInput<
    TAccountMultisig,
    TAccountMember,
    TAccountProposal,
    TAccountBatch,
    TAccountTransaction
  >,
  config?: { programAddress?: TProgramAddress }
): BatchExecuteTransactionInstruction<
  TProgramAddress,
  TAccountMultisig,
  TAccountMember,
  TAccountProposal,
  TAccountBatch,
  TAccountTransaction
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    multisig: { value: input.multisig ?? null, isWritable: false },
    member: { value: input.member ?? null, isWritable: false },
    proposal: { value: input.proposal ?? null, isWritable: true },
    batch: { value: input.batch ?? null, isWritable: true },
    transaction: { value: input.transaction ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.multisig),
      getAccountMeta(accounts.member),
      getAccountMeta(accounts.proposal),
      getAccountMeta(accounts.batch),
      getAccountMeta(accounts.transaction),
    ],
    programAddress,
    data: getBatchExecuteTransactionInstructionDataEncoder().encode({}),
  } as BatchExecuteTransactionInstruction<
    TProgramAddress,
    TAccountMultisig,
    TAccountMember,
    TAccountProposal,
    TAccountBatch,
    TAccountTransaction
  >;

  return instruction;
}

export type ParsedBatchExecuteTransactionInstruction<
  TProgram extends string = typeof SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Multisig account this batch belongs to. */
    multisig: TAccountMetas[0];
    /** Member of the multisig. */
    member: TAccountMetas[1];
    /**
     * The proposal account associated with the batch.
     * If `transaction` is the last in the batch, the `proposal` status will be set to `Executed`.
     */

    proposal: TAccountMetas[2];
    batch: TAccountMetas[3];
    /** Batch transaction to execute. */
    transaction: TAccountMetas[4];
  };
  data: BatchExecuteTransactionInstructionData;
};

export function parseBatchExecuteTransactionInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedBatchExecuteTransactionInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      multisig: getNextAccount(),
      member: getNextAccount(),
      proposal: getNextAccount(),
      batch: getNextAccount(),
      transaction: getNextAccount(),
    },
    data: getBatchExecuteTransactionInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
