/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const PROGRAM_CONFIG_SET_MULTISIG_CREATION_FEE_DISCRIMINATOR =
  new Uint8Array([101, 160, 249, 63, 154, 215, 153, 13]);

export function getProgramConfigSetMultisigCreationFeeDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    PROGRAM_CONFIG_SET_MULTISIG_CREATION_FEE_DISCRIMINATOR
  );
}

export type ProgramConfigSetMultisigCreationFeeInstruction<
  TProgram extends string = typeof SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS,
  TAccountProgramConfig extends string | AccountMeta<string> = string,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountProgramConfig extends string
        ? WritableAccount<TAccountProgramConfig>
        : TAccountProgramConfig,
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type ProgramConfigSetMultisigCreationFeeInstructionData = {
  discriminator: ReadonlyUint8Array;
  newMultisigCreationFee: bigint;
};

export type ProgramConfigSetMultisigCreationFeeInstructionDataArgs = {
  newMultisigCreationFee: number | bigint;
};

export function getProgramConfigSetMultisigCreationFeeInstructionDataEncoder(): FixedSizeEncoder<ProgramConfigSetMultisigCreationFeeInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['newMultisigCreationFee', getU64Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: PROGRAM_CONFIG_SET_MULTISIG_CREATION_FEE_DISCRIMINATOR,
    })
  );
}

export function getProgramConfigSetMultisigCreationFeeInstructionDataDecoder(): FixedSizeDecoder<ProgramConfigSetMultisigCreationFeeInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['newMultisigCreationFee', getU64Decoder()],
  ]);
}

export function getProgramConfigSetMultisigCreationFeeInstructionDataCodec(): FixedSizeCodec<
  ProgramConfigSetMultisigCreationFeeInstructionDataArgs,
  ProgramConfigSetMultisigCreationFeeInstructionData
> {
  return combineCodec(
    getProgramConfigSetMultisigCreationFeeInstructionDataEncoder(),
    getProgramConfigSetMultisigCreationFeeInstructionDataDecoder()
  );
}

export type ProgramConfigSetMultisigCreationFeeInput<
  TAccountProgramConfig extends string = string,
  TAccountAuthority extends string = string,
> = {
  programConfig: Address<TAccountProgramConfig>;
  authority: TransactionSigner<TAccountAuthority>;
  newMultisigCreationFee: ProgramConfigSetMultisigCreationFeeInstructionDataArgs['newMultisigCreationFee'];
};

export function getProgramConfigSetMultisigCreationFeeInstruction<
  TAccountProgramConfig extends string,
  TAccountAuthority extends string,
  TProgramAddress extends
    Address = typeof SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS,
>(
  input: ProgramConfigSetMultisigCreationFeeInput<
    TAccountProgramConfig,
    TAccountAuthority
  >,
  config?: { programAddress?: TProgramAddress }
): ProgramConfigSetMultisigCreationFeeInstruction<
  TProgramAddress,
  TAccountProgramConfig,
  TAccountAuthority
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    programConfig: { value: input.programConfig ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.programConfig),
      getAccountMeta(accounts.authority),
    ],
    programAddress,
    data: getProgramConfigSetMultisigCreationFeeInstructionDataEncoder().encode(
      args as ProgramConfigSetMultisigCreationFeeInstructionDataArgs
    ),
  } as ProgramConfigSetMultisigCreationFeeInstruction<
    TProgramAddress,
    TAccountProgramConfig,
    TAccountAuthority
  >;

  return instruction;
}

export type ParsedProgramConfigSetMultisigCreationFeeInstruction<
  TProgram extends string = typeof SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    programConfig: TAccountMetas[0];
    authority: TAccountMetas[1];
  };
  data: ProgramConfigSetMultisigCreationFeeInstructionData;
};

export function parseProgramConfigSetMultisigCreationFeeInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedProgramConfigSetMultisigCreationFeeInstruction<
  TProgram,
  TAccountMetas
> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      programConfig: getNextAccount(),
      authority: getNextAccount(),
    },
    data: getProgramConfigSetMultisigCreationFeeInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
