/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const PROGRAM_CONFIG_SET_AUTHORITY_DISCRIMINATOR = new Uint8Array([
  238, 242, 36, 181, 32, 143, 216, 75,
]);

export function getProgramConfigSetAuthorityDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    PROGRAM_CONFIG_SET_AUTHORITY_DISCRIMINATOR
  );
}

export type ProgramConfigSetAuthorityInstruction<
  TProgram extends string = typeof SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS,
  TAccountProgramConfig extends string | AccountMeta<string> = string,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountProgramConfig extends string
        ? WritableAccount<TAccountProgramConfig>
        : TAccountProgramConfig,
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type ProgramConfigSetAuthorityInstructionData = {
  discriminator: ReadonlyUint8Array;
  newAuthority: Address;
};

export type ProgramConfigSetAuthorityInstructionDataArgs = {
  newAuthority: Address;
};

export function getProgramConfigSetAuthorityInstructionDataEncoder(): FixedSizeEncoder<ProgramConfigSetAuthorityInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['newAuthority', getAddressEncoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: PROGRAM_CONFIG_SET_AUTHORITY_DISCRIMINATOR,
    })
  );
}

export function getProgramConfigSetAuthorityInstructionDataDecoder(): FixedSizeDecoder<ProgramConfigSetAuthorityInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['newAuthority', getAddressDecoder()],
  ]);
}

export function getProgramConfigSetAuthorityInstructionDataCodec(): FixedSizeCodec<
  ProgramConfigSetAuthorityInstructionDataArgs,
  ProgramConfigSetAuthorityInstructionData
> {
  return combineCodec(
    getProgramConfigSetAuthorityInstructionDataEncoder(),
    getProgramConfigSetAuthorityInstructionDataDecoder()
  );
}

export type ProgramConfigSetAuthorityInput<
  TAccountProgramConfig extends string = string,
  TAccountAuthority extends string = string,
> = {
  programConfig: Address<TAccountProgramConfig>;
  authority: TransactionSigner<TAccountAuthority>;
  newAuthority: ProgramConfigSetAuthorityInstructionDataArgs['newAuthority'];
};

export function getProgramConfigSetAuthorityInstruction<
  TAccountProgramConfig extends string,
  TAccountAuthority extends string,
  TProgramAddress extends
    Address = typeof SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS,
>(
  input: ProgramConfigSetAuthorityInput<
    TAccountProgramConfig,
    TAccountAuthority
  >,
  config?: { programAddress?: TProgramAddress }
): ProgramConfigSetAuthorityInstruction<
  TProgramAddress,
  TAccountProgramConfig,
  TAccountAuthority
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    programConfig: { value: input.programConfig ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.programConfig),
      getAccountMeta(accounts.authority),
    ],
    programAddress,
    data: getProgramConfigSetAuthorityInstructionDataEncoder().encode(
      args as ProgramConfigSetAuthorityInstructionDataArgs
    ),
  } as ProgramConfigSetAuthorityInstruction<
    TProgramAddress,
    TAccountProgramConfig,
    TAccountAuthority
  >;

  return instruction;
}

export type ParsedProgramConfigSetAuthorityInstruction<
  TProgram extends string = typeof SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    programConfig: TAccountMetas[0];
    authority: TAccountMetas[1];
  };
  data: ProgramConfigSetAuthorityInstructionData;
};

export function parseProgramConfigSetAuthorityInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedProgramConfigSetAuthorityInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      programConfig: getNextAccount(),
      authority: getNextAccount(),
    },
    data: getProgramConfigSetAuthorityInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
