/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const TRANSACTION_BUFFER_EXTEND_DISCRIMINATOR = new Uint8Array([
  230, 157, 67, 56, 5, 238, 245, 146,
]);

export function getTransactionBufferExtendDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    TRANSACTION_BUFFER_EXTEND_DISCRIMINATOR
  );
}

export type TransactionBufferExtendInstruction<
  TProgram extends string = typeof SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS,
  TAccountMultisig extends string | AccountMeta<string> = string,
  TAccountTransactionBuffer extends string | AccountMeta<string> = string,
  TAccountCreator extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountMultisig extends string
        ? ReadonlyAccount<TAccountMultisig>
        : TAccountMultisig,
      TAccountTransactionBuffer extends string
        ? WritableAccount<TAccountTransactionBuffer>
        : TAccountTransactionBuffer,
      TAccountCreator extends string
        ? ReadonlySignerAccount<TAccountCreator> &
            AccountSignerMeta<TAccountCreator>
        : TAccountCreator,
      ...TRemainingAccounts,
    ]
  >;

export type TransactionBufferExtendInstructionData = {
  discriminator: ReadonlyUint8Array;
  buffer: ReadonlyUint8Array;
};

export type TransactionBufferExtendInstructionDataArgs = {
  buffer: ReadonlyUint8Array;
};

export function getTransactionBufferExtendInstructionDataEncoder(): Encoder<TransactionBufferExtendInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['buffer', addEncoderSizePrefix(getBytesEncoder(), getU32Encoder())],
    ]),
    (value) => ({
      ...value,
      discriminator: TRANSACTION_BUFFER_EXTEND_DISCRIMINATOR,
    })
  );
}

export function getTransactionBufferExtendInstructionDataDecoder(): Decoder<TransactionBufferExtendInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['buffer', addDecoderSizePrefix(getBytesDecoder(), getU32Decoder())],
  ]);
}

export function getTransactionBufferExtendInstructionDataCodec(): Codec<
  TransactionBufferExtendInstructionDataArgs,
  TransactionBufferExtendInstructionData
> {
  return combineCodec(
    getTransactionBufferExtendInstructionDataEncoder(),
    getTransactionBufferExtendInstructionDataDecoder()
  );
}

export type TransactionBufferExtendInput<
  TAccountMultisig extends string = string,
  TAccountTransactionBuffer extends string = string,
  TAccountCreator extends string = string,
> = {
  multisig: Address<TAccountMultisig>;
  transactionBuffer: Address<TAccountTransactionBuffer>;
  /** The member of the multisig that created the TransactionBuffer. */
  creator: TransactionSigner<TAccountCreator>;
  buffer: TransactionBufferExtendInstructionDataArgs['buffer'];
};

export function getTransactionBufferExtendInstruction<
  TAccountMultisig extends string,
  TAccountTransactionBuffer extends string,
  TAccountCreator extends string,
  TProgramAddress extends
    Address = typeof SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS,
>(
  input: TransactionBufferExtendInput<
    TAccountMultisig,
    TAccountTransactionBuffer,
    TAccountCreator
  >,
  config?: { programAddress?: TProgramAddress }
): TransactionBufferExtendInstruction<
  TProgramAddress,
  TAccountMultisig,
  TAccountTransactionBuffer,
  TAccountCreator
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    multisig: { value: input.multisig ?? null, isWritable: false },
    transactionBuffer: {
      value: input.transactionBuffer ?? null,
      isWritable: true,
    },
    creator: { value: input.creator ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.multisig),
      getAccountMeta(accounts.transactionBuffer),
      getAccountMeta(accounts.creator),
    ],
    programAddress,
    data: getTransactionBufferExtendInstructionDataEncoder().encode(
      args as TransactionBufferExtendInstructionDataArgs
    ),
  } as TransactionBufferExtendInstruction<
    TProgramAddress,
    TAccountMultisig,
    TAccountTransactionBuffer,
    TAccountCreator
  >;

  return instruction;
}

export type ParsedTransactionBufferExtendInstruction<
  TProgram extends string = typeof SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    multisig: TAccountMetas[0];
    transactionBuffer: TAccountMetas[1];
    /** The member of the multisig that created the TransactionBuffer. */
    creator: TAccountMetas[2];
  };
  data: TransactionBufferExtendInstructionData;
};

export function parseTransactionBufferExtendInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedTransactionBufferExtendInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      multisig: getNextAccount(),
      transactionBuffer: getNextAccount(),
      creator: getNextAccount(),
    },
    data: getTransactionBufferExtendInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
