/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const TRANSACTION_BUFFER_CLOSE_DISCRIMINATOR = new Uint8Array([
  17, 182, 208, 228, 136, 24, 178, 102,
]);

export function getTransactionBufferCloseDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    TRANSACTION_BUFFER_CLOSE_DISCRIMINATOR
  );
}

export type TransactionBufferCloseInstruction<
  TProgram extends string = typeof SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS,
  TAccountMultisig extends string | AccountMeta<string> = string,
  TAccountTransactionBuffer extends string | AccountMeta<string> = string,
  TAccountCreator extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountMultisig extends string
        ? ReadonlyAccount<TAccountMultisig>
        : TAccountMultisig,
      TAccountTransactionBuffer extends string
        ? WritableAccount<TAccountTransactionBuffer>
        : TAccountTransactionBuffer,
      TAccountCreator extends string
        ? ReadonlySignerAccount<TAccountCreator> &
            AccountSignerMeta<TAccountCreator>
        : TAccountCreator,
      ...TRemainingAccounts,
    ]
  >;

export type TransactionBufferCloseInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type TransactionBufferCloseInstructionDataArgs = {};

export function getTransactionBufferCloseInstructionDataEncoder(): FixedSizeEncoder<TransactionBufferCloseInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({
      ...value,
      discriminator: TRANSACTION_BUFFER_CLOSE_DISCRIMINATOR,
    })
  );
}

export function getTransactionBufferCloseInstructionDataDecoder(): FixedSizeDecoder<TransactionBufferCloseInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getTransactionBufferCloseInstructionDataCodec(): FixedSizeCodec<
  TransactionBufferCloseInstructionDataArgs,
  TransactionBufferCloseInstructionData
> {
  return combineCodec(
    getTransactionBufferCloseInstructionDataEncoder(),
    getTransactionBufferCloseInstructionDataDecoder()
  );
}

export type TransactionBufferCloseInput<
  TAccountMultisig extends string = string,
  TAccountTransactionBuffer extends string = string,
  TAccountCreator extends string = string,
> = {
  multisig: Address<TAccountMultisig>;
  transactionBuffer: Address<TAccountTransactionBuffer>;
  /** The member of the multisig that created the TransactionBuffer. */
  creator: TransactionSigner<TAccountCreator>;
};

export function getTransactionBufferCloseInstruction<
  TAccountMultisig extends string,
  TAccountTransactionBuffer extends string,
  TAccountCreator extends string,
  TProgramAddress extends
    Address = typeof SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS,
>(
  input: TransactionBufferCloseInput<
    TAccountMultisig,
    TAccountTransactionBuffer,
    TAccountCreator
  >,
  config?: { programAddress?: TProgramAddress }
): TransactionBufferCloseInstruction<
  TProgramAddress,
  TAccountMultisig,
  TAccountTransactionBuffer,
  TAccountCreator
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    multisig: { value: input.multisig ?? null, isWritable: false },
    transactionBuffer: {
      value: input.transactionBuffer ?? null,
      isWritable: true,
    },
    creator: { value: input.creator ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.multisig),
      getAccountMeta(accounts.transactionBuffer),
      getAccountMeta(accounts.creator),
    ],
    programAddress,
    data: getTransactionBufferCloseInstructionDataEncoder().encode({}),
  } as TransactionBufferCloseInstruction<
    TProgramAddress,
    TAccountMultisig,
    TAccountTransactionBuffer,
    TAccountCreator
  >;

  return instruction;
}

export type ParsedTransactionBufferCloseInstruction<
  TProgram extends string = typeof SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    multisig: TAccountMetas[0];
    transactionBuffer: TAccountMetas[1];
    /** The member of the multisig that created the TransactionBuffer. */
    creator: TAccountMetas[2];
  };
  data: TransactionBufferCloseInstructionData;
};

export function parseTransactionBufferCloseInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedTransactionBufferCloseInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      multisig: getNextAccount(),
      transactionBuffer: getNextAccount(),
      creator: getNextAccount(),
    },
    data: getTransactionBufferCloseInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
