/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU32Decoder,
  getU32Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const TRANSACTION_BUFFER_CREATE_DISCRIMINATOR = new Uint8Array([
  245, 201, 113, 108, 37, 63, 29, 89,
]);

export function getTransactionBufferCreateDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    TRANSACTION_BUFFER_CREATE_DISCRIMINATOR
  );
}

export type TransactionBufferCreateInstruction<
  TProgram extends string = typeof SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS,
  TAccountMultisig extends string | AccountMeta<string> = string,
  TAccountTransactionBuffer extends string | AccountMeta<string> = string,
  TAccountCreator extends string | AccountMeta<string> = string,
  TAccountRentPayer extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountMultisig extends string
        ? ReadonlyAccount<TAccountMultisig>
        : TAccountMultisig,
      TAccountTransactionBuffer extends string
        ? WritableAccount<TAccountTransactionBuffer>
        : TAccountTransactionBuffer,
      TAccountCreator extends string
        ? ReadonlySignerAccount<TAccountCreator> &
            AccountSignerMeta<TAccountCreator>
        : TAccountCreator,
      TAccountRentPayer extends string
        ? WritableSignerAccount<TAccountRentPayer> &
            AccountSignerMeta<TAccountRentPayer>
        : TAccountRentPayer,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type TransactionBufferCreateInstructionData = {
  discriminator: ReadonlyUint8Array;
  /** Index of the buffer account to seed the account derivation */
  bufferIndex: number;
  /** Index of the vault this transaction belongs to. */
  vaultIndex: number;
  /** Hash of the final assembled transaction message. */
  finalBufferHash: ReadonlyUint8Array;
  /** Final size of the buffer. */
  finalBufferSize: number;
  /** Initial slice of the buffer. */
  buffer: ReadonlyUint8Array;
};

export type TransactionBufferCreateInstructionDataArgs = {
  /** Index of the buffer account to seed the account derivation */
  bufferIndex: number;
  /** Index of the vault this transaction belongs to. */
  vaultIndex: number;
  /** Hash of the final assembled transaction message. */
  finalBufferHash: ReadonlyUint8Array;
  /** Final size of the buffer. */
  finalBufferSize: number;
  /** Initial slice of the buffer. */
  buffer: ReadonlyUint8Array;
};

export function getTransactionBufferCreateInstructionDataEncoder(): Encoder<TransactionBufferCreateInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['bufferIndex', getU8Encoder()],
      ['vaultIndex', getU8Encoder()],
      ['finalBufferHash', fixEncoderSize(getBytesEncoder(), 32)],
      ['finalBufferSize', getU16Encoder()],
      ['buffer', addEncoderSizePrefix(getBytesEncoder(), getU32Encoder())],
    ]),
    (value) => ({
      ...value,
      discriminator: TRANSACTION_BUFFER_CREATE_DISCRIMINATOR,
    })
  );
}

export function getTransactionBufferCreateInstructionDataDecoder(): Decoder<TransactionBufferCreateInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['bufferIndex', getU8Decoder()],
    ['vaultIndex', getU8Decoder()],
    ['finalBufferHash', fixDecoderSize(getBytesDecoder(), 32)],
    ['finalBufferSize', getU16Decoder()],
    ['buffer', addDecoderSizePrefix(getBytesDecoder(), getU32Decoder())],
  ]);
}

export function getTransactionBufferCreateInstructionDataCodec(): Codec<
  TransactionBufferCreateInstructionDataArgs,
  TransactionBufferCreateInstructionData
> {
  return combineCodec(
    getTransactionBufferCreateInstructionDataEncoder(),
    getTransactionBufferCreateInstructionDataDecoder()
  );
}

export type TransactionBufferCreateInput<
  TAccountMultisig extends string = string,
  TAccountTransactionBuffer extends string = string,
  TAccountCreator extends string = string,
  TAccountRentPayer extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  multisig: Address<TAccountMultisig>;
  transactionBuffer: Address<TAccountTransactionBuffer>;
  /** The member of the multisig that is creating the transaction. */
  creator: TransactionSigner<TAccountCreator>;
  /** The payer for the transaction account rent. */
  rentPayer: TransactionSigner<TAccountRentPayer>;
  systemProgram?: Address<TAccountSystemProgram>;
  bufferIndex: TransactionBufferCreateInstructionDataArgs['bufferIndex'];
  vaultIndex: TransactionBufferCreateInstructionDataArgs['vaultIndex'];
  finalBufferHash: TransactionBufferCreateInstructionDataArgs['finalBufferHash'];
  finalBufferSize: TransactionBufferCreateInstructionDataArgs['finalBufferSize'];
  buffer: TransactionBufferCreateInstructionDataArgs['buffer'];
};

export function getTransactionBufferCreateInstruction<
  TAccountMultisig extends string,
  TAccountTransactionBuffer extends string,
  TAccountCreator extends string,
  TAccountRentPayer extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends
    Address = typeof SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS,
>(
  input: TransactionBufferCreateInput<
    TAccountMultisig,
    TAccountTransactionBuffer,
    TAccountCreator,
    TAccountRentPayer,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): TransactionBufferCreateInstruction<
  TProgramAddress,
  TAccountMultisig,
  TAccountTransactionBuffer,
  TAccountCreator,
  TAccountRentPayer,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    multisig: { value: input.multisig ?? null, isWritable: false },
    transactionBuffer: {
      value: input.transactionBuffer ?? null,
      isWritable: true,
    },
    creator: { value: input.creator ?? null, isWritable: false },
    rentPayer: { value: input.rentPayer ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.multisig),
      getAccountMeta(accounts.transactionBuffer),
      getAccountMeta(accounts.creator),
      getAccountMeta(accounts.rentPayer),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getTransactionBufferCreateInstructionDataEncoder().encode(
      args as TransactionBufferCreateInstructionDataArgs
    ),
  } as TransactionBufferCreateInstruction<
    TProgramAddress,
    TAccountMultisig,
    TAccountTransactionBuffer,
    TAccountCreator,
    TAccountRentPayer,
    TAccountSystemProgram
  >;

  return instruction;
}

export type ParsedTransactionBufferCreateInstruction<
  TProgram extends string = typeof SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    multisig: TAccountMetas[0];
    transactionBuffer: TAccountMetas[1];
    /** The member of the multisig that is creating the transaction. */
    creator: TAccountMetas[2];
    /** The payer for the transaction account rent. */
    rentPayer: TAccountMetas[3];
    systemProgram: TAccountMetas[4];
  };
  data: TransactionBufferCreateInstructionData;
};

export function parseTransactionBufferCreateInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedTransactionBufferCreateInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      multisig: getNextAccount(),
      transactionBuffer: getNextAccount(),
      creator: getNextAccount(),
      rentPayer: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getTransactionBufferCreateInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
