/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type WritableAccount,
} from '@solana/kit';
import { SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const VAULT_TRANSACTION_ACCOUNTS_CLOSE_DISCRIMINATOR = new Uint8Array([
  196, 71, 187, 176, 2, 35, 170, 165,
]);

export function getVaultTransactionAccountsCloseDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    VAULT_TRANSACTION_ACCOUNTS_CLOSE_DISCRIMINATOR
  );
}

export type VaultTransactionAccountsCloseInstruction<
  TProgram extends string = typeof SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS,
  TAccountMultisig extends string | AccountMeta<string> = string,
  TAccountProposal extends string | AccountMeta<string> = string,
  TAccountTransaction extends string | AccountMeta<string> = string,
  TAccountRentCollector extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountMultisig extends string
        ? ReadonlyAccount<TAccountMultisig>
        : TAccountMultisig,
      TAccountProposal extends string
        ? WritableAccount<TAccountProposal>
        : TAccountProposal,
      TAccountTransaction extends string
        ? WritableAccount<TAccountTransaction>
        : TAccountTransaction,
      TAccountRentCollector extends string
        ? WritableAccount<TAccountRentCollector>
        : TAccountRentCollector,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type VaultTransactionAccountsCloseInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type VaultTransactionAccountsCloseInstructionDataArgs = {};

export function getVaultTransactionAccountsCloseInstructionDataEncoder(): FixedSizeEncoder<VaultTransactionAccountsCloseInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({
      ...value,
      discriminator: VAULT_TRANSACTION_ACCOUNTS_CLOSE_DISCRIMINATOR,
    })
  );
}

export function getVaultTransactionAccountsCloseInstructionDataDecoder(): FixedSizeDecoder<VaultTransactionAccountsCloseInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getVaultTransactionAccountsCloseInstructionDataCodec(): FixedSizeCodec<
  VaultTransactionAccountsCloseInstructionDataArgs,
  VaultTransactionAccountsCloseInstructionData
> {
  return combineCodec(
    getVaultTransactionAccountsCloseInstructionDataEncoder(),
    getVaultTransactionAccountsCloseInstructionDataDecoder()
  );
}

export type VaultTransactionAccountsCloseInput<
  TAccountMultisig extends string = string,
  TAccountProposal extends string = string,
  TAccountTransaction extends string = string,
  TAccountRentCollector extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  multisig: Address<TAccountMultisig>;
  /** the logic within `vault_transaction_accounts_close` does the rest of the checks. */
  proposal: Address<TAccountProposal>;
  /** VaultTransaction corresponding to the `proposal`. */
  transaction: Address<TAccountTransaction>;
  /** The rent collector. */
  rentCollector: Address<TAccountRentCollector>;
  systemProgram?: Address<TAccountSystemProgram>;
};

export function getVaultTransactionAccountsCloseInstruction<
  TAccountMultisig extends string,
  TAccountProposal extends string,
  TAccountTransaction extends string,
  TAccountRentCollector extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends
    Address = typeof SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS,
>(
  input: VaultTransactionAccountsCloseInput<
    TAccountMultisig,
    TAccountProposal,
    TAccountTransaction,
    TAccountRentCollector,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): VaultTransactionAccountsCloseInstruction<
  TProgramAddress,
  TAccountMultisig,
  TAccountProposal,
  TAccountTransaction,
  TAccountRentCollector,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    multisig: { value: input.multisig ?? null, isWritable: false },
    proposal: { value: input.proposal ?? null, isWritable: true },
    transaction: { value: input.transaction ?? null, isWritable: true },
    rentCollector: { value: input.rentCollector ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.multisig),
      getAccountMeta(accounts.proposal),
      getAccountMeta(accounts.transaction),
      getAccountMeta(accounts.rentCollector),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getVaultTransactionAccountsCloseInstructionDataEncoder().encode({}),
  } as VaultTransactionAccountsCloseInstruction<
    TProgramAddress,
    TAccountMultisig,
    TAccountProposal,
    TAccountTransaction,
    TAccountRentCollector,
    TAccountSystemProgram
  >;

  return instruction;
}

export type ParsedVaultTransactionAccountsCloseInstruction<
  TProgram extends string = typeof SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    multisig: TAccountMetas[0];
    /** the logic within `vault_transaction_accounts_close` does the rest of the checks. */
    proposal: TAccountMetas[1];
    /** VaultTransaction corresponding to the `proposal`. */
    transaction: TAccountMetas[2];
    /** The rent collector. */
    rentCollector: TAccountMetas[3];
    systemProgram: TAccountMetas[4];
  };
  data: VaultTransactionAccountsCloseInstructionData;
};

export function parseVaultTransactionAccountsCloseInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedVaultTransactionAccountsCloseInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      multisig: getNextAccount(),
      proposal: getNextAccount(),
      transaction: getNextAccount(),
      rentCollector: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getVaultTransactionAccountsCloseInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
