/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type WritableAccount,
} from '@solana/kit';
import { SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const VAULT_BATCH_TRANSACTION_ACCOUNT_CLOSE_DISCRIMINATOR =
  new Uint8Array([134, 18, 19, 106, 129, 68, 97, 247]);

export function getVaultBatchTransactionAccountCloseDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    VAULT_BATCH_TRANSACTION_ACCOUNT_CLOSE_DISCRIMINATOR
  );
}

export type VaultBatchTransactionAccountCloseInstruction<
  TProgram extends string = typeof SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS,
  TAccountMultisig extends string | AccountMeta<string> = string,
  TAccountProposal extends string | AccountMeta<string> = string,
  TAccountBatch extends string | AccountMeta<string> = string,
  TAccountTransaction extends string | AccountMeta<string> = string,
  TAccountRentCollector extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountMultisig extends string
        ? ReadonlyAccount<TAccountMultisig>
        : TAccountMultisig,
      TAccountProposal extends string
        ? ReadonlyAccount<TAccountProposal>
        : TAccountProposal,
      TAccountBatch extends string
        ? WritableAccount<TAccountBatch>
        : TAccountBatch,
      TAccountTransaction extends string
        ? WritableAccount<TAccountTransaction>
        : TAccountTransaction,
      TAccountRentCollector extends string
        ? WritableAccount<TAccountRentCollector>
        : TAccountRentCollector,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type VaultBatchTransactionAccountCloseInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type VaultBatchTransactionAccountCloseInstructionDataArgs = {};

export function getVaultBatchTransactionAccountCloseInstructionDataEncoder(): FixedSizeEncoder<VaultBatchTransactionAccountCloseInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({
      ...value,
      discriminator: VAULT_BATCH_TRANSACTION_ACCOUNT_CLOSE_DISCRIMINATOR,
    })
  );
}

export function getVaultBatchTransactionAccountCloseInstructionDataDecoder(): FixedSizeDecoder<VaultBatchTransactionAccountCloseInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getVaultBatchTransactionAccountCloseInstructionDataCodec(): FixedSizeCodec<
  VaultBatchTransactionAccountCloseInstructionDataArgs,
  VaultBatchTransactionAccountCloseInstructionData
> {
  return combineCodec(
    getVaultBatchTransactionAccountCloseInstructionDataEncoder(),
    getVaultBatchTransactionAccountCloseInstructionDataDecoder()
  );
}

export type VaultBatchTransactionAccountCloseInput<
  TAccountMultisig extends string = string,
  TAccountProposal extends string = string,
  TAccountBatch extends string = string,
  TAccountTransaction extends string = string,
  TAccountRentCollector extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  multisig: Address<TAccountMultisig>;
  proposal: Address<TAccountProposal>;
  /** `Batch` corresponding to the `proposal`. */
  batch: Address<TAccountBatch>;
  /**
   * `VaultBatchTransaction` account to close.
   * The transaction must be the current last one in the batch.
   */
  transaction: Address<TAccountTransaction>;
  /** The rent collector. */
  rentCollector: Address<TAccountRentCollector>;
  systemProgram?: Address<TAccountSystemProgram>;
};

export function getVaultBatchTransactionAccountCloseInstruction<
  TAccountMultisig extends string,
  TAccountProposal extends string,
  TAccountBatch extends string,
  TAccountTransaction extends string,
  TAccountRentCollector extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends
    Address = typeof SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS,
>(
  input: VaultBatchTransactionAccountCloseInput<
    TAccountMultisig,
    TAccountProposal,
    TAccountBatch,
    TAccountTransaction,
    TAccountRentCollector,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): VaultBatchTransactionAccountCloseInstruction<
  TProgramAddress,
  TAccountMultisig,
  TAccountProposal,
  TAccountBatch,
  TAccountTransaction,
  TAccountRentCollector,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    multisig: { value: input.multisig ?? null, isWritable: false },
    proposal: { value: input.proposal ?? null, isWritable: false },
    batch: { value: input.batch ?? null, isWritable: true },
    transaction: { value: input.transaction ?? null, isWritable: true },
    rentCollector: { value: input.rentCollector ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.multisig),
      getAccountMeta(accounts.proposal),
      getAccountMeta(accounts.batch),
      getAccountMeta(accounts.transaction),
      getAccountMeta(accounts.rentCollector),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getVaultBatchTransactionAccountCloseInstructionDataEncoder().encode(
      {}
    ),
  } as VaultBatchTransactionAccountCloseInstruction<
    TProgramAddress,
    TAccountMultisig,
    TAccountProposal,
    TAccountBatch,
    TAccountTransaction,
    TAccountRentCollector,
    TAccountSystemProgram
  >;

  return instruction;
}

export type ParsedVaultBatchTransactionAccountCloseInstruction<
  TProgram extends string = typeof SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    multisig: TAccountMetas[0];
    proposal: TAccountMetas[1];
    /** `Batch` corresponding to the `proposal`. */
    batch: TAccountMetas[2];
    /**
     * `VaultBatchTransaction` account to close.
     * The transaction must be the current last one in the batch.
     */

    transaction: TAccountMetas[3];
    /** The rent collector. */
    rentCollector: TAccountMetas[4];
    systemProgram: TAccountMetas[5];
  };
  data: VaultBatchTransactionAccountCloseInstructionData;
};

export function parseVaultBatchTransactionAccountCloseInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedVaultBatchTransactionAccountCloseInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      multisig: getNextAccount(),
      proposal: getNextAccount(),
      batch: getNextAccount(),
      transaction: getNextAccount(),
      rentCollector: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getVaultBatchTransactionAccountCloseInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
